### ISSUE TITLE
メニューバーアイコンの表示・非表示の切り替え

### ISSUE THREAD

**Issue by uetchy** [iMasanari/cmd-eikana#1]
Karabinerのように、メニューバーアイコンの表示・非表示を切り替える機能があると、ユーティリティアプリとして、より使いやすいように思います。
もしかすると、実装にはバックグラウンドヘルパーが必要になってくるかもしれません。
どう思いますか？

**Comment by iMasanari** [comment]
ただいま実装中です
しばらくお待ちください！

**Comment by iMasanari** [comment]
実装しました (f861e68)
こんな感じでよろしいでしょうか

**Comment by uetchy** [comment]
お疲れ様です！
しかし、Sierra上で動作確認をしてみたところ、アイコンの表示・非表示に関わらず英かなの切り替えが上手く出来ないようです😱

**Comment by uetchy** [comment]
また、起動するたびにアクセシビリティの許可がリセットされる挙動を見せています。

**Comment by uetchy** [comment]
以前のバージョンのアプリの設定を削除し、再起動してからアプリを起動すると正常に切り替えが出来ますが、その後設定画面からアイコンの非表示オプションを有効すると、切り替えが出来なくなりました。
ただし、非表示オプションを有効にした後にアプリを終了し、再度起動し直すことで正常に切り替えが出来るようになりました。
一方で、アプリが起動している状態で再度アプリアイコンから設定画面を呼び出すと、切り替えが出来なくなります。

**Comment by iMasanari** [comment]
報告ありがとうございます。
今朝twitterでもアクセシビリティ機能への許可がうまくいかない報告があり、現在調査中です。
サブ環境で試したところ同じ症状になり、同じく再起動で治りました。（bundle idを変えたことが原因の心当たりにあるので後で試してみます）

また後半の切り替えが出来ない症状は、設定画面が最前面の状態なのかなと思います。
（キーの監視が多分他のアプリのときのみなので、アプリ中でも切り替えれるようにしておきます）
もし設定画面を閉じる、または他のアプリをアクティブにしても同じ症状が出る場合はまた報告お願いします。

**Comment by matsuda0707** [comment]
私もKarabinerユーザーでしたが、よりシンプルなこのソフトを発見し使用していますが、キーボードとしてPC用のJISキーボードの変換、無変換、あるいは左右のコントロールキーで同じ機能をサポートできないでしょうか？

**Comment by uetchy** [comment]
@iMasanari 1.0.4からこのissueで言及されている問題は全て直ったようです！

**Comment by kkitade** [comment]
便利にKarabinerから移行させていただきました。
で、右optionが死んでいる気がします。左は生きています。
改善要望です。

**Comment by iMasanari** [comment]
@kkitade こちらの環境では右optionの問題は確認できませんでした。
アプリを起動した状態と終了した状態でもう一度確認し、もし問題が続くようであれば[New issues](https://github.com/iMasanari/cmd-eikana/issues/new)として報告お願いします。
