### ISSUE TITLE
メディアキー、音量キー、消音キーのサポート

### ISSUE THREAD

**Issue by leopard-gecko** [iMasanari/cmd-eikana#10]
非純正キーボードを使用していますが、「Shortcuts」の設定画面でメディアキーと音量キーと消音キーが認識されないようです。
環境にもよるのかもしれませんが、もし未実装なのであれば対応していただけるとありがたいです。

**Comment by iMasanari** [comment]
⌘英かなが採用している方法では音量キーなどのキーが取得できないため、今のところ対応の予定はありません。取得方法がわかり次第作業に入るという感じになると思います。

しかし、[tekezo](https://github.com/tekezo)さんが開発している[Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements)を使用することで、メディアキーを別のキーに割り振ることができます。こちらはキーを別のキーに置き換えるためCommand-Xといったショートカットを登録することはできませんが、Karabiner-Elementsと⌘英かなを併用することで対応できるかと思います。

しかし、私が試した非純正キーボードではメディアキーではない（ファンクションキーと一緒になっていない）音量キーと消音キーはリマップできませんでした。

下のスクリーンショットでは、Karabiner-Elementsで音量ダウン(F11)をXキーに、Karabiner-Elementsと⌘英かなを併用し音量アップ(F12)をF19（普段使わないキー）を経由してCommand-Xにリマップしています。

<img width="799" alt="2016-11-02 9 37 41" src="https://cloud.githubusercontent.com/assets/20771486/19912759/3becf99c-a0e0-11e6-9975-60291b08df97.png">

**Comment by leopard-gecko** [comment]
私もKarabiner-Elementsで非純正キーボードの音量キーと消音キーのリマップを試してみましたが、同様にリマップできませんでした。
Karabiner-Elementsはシステム環境設定のキーボードの設定も無効にしてしまうなど私にとっては使いにくい点が多々あり、こちらのアプリの方に期待しております。
ご丁寧に検証までしていただきありがとうございました。

**Comment by iMasanari** [comment]
遅くなりましたがv2.2.0にて対応いたしました
宜しければお使いください
