### ISSUE TITLE
Key Remap で Command の左右の区別化希望

### ISSUE THREAD

**Issue by MasaYan24** [iMasanari/cmd-eikana#11]
単体の Command_L と Command_R が区別できるようなので、
ユーザーの Key Remap でも Command_L と Command_R + 何かのキー
のときにも左右の区別を付けるようにならないでしょうか。

Karabiner からの乗り換えで、vi-like な使用が必要で、
Command_R+h = ←
Command_R+j = ↓
Command_R+k = ↑
Command_R+l = →
のように割り当てるのと同時に、
Command_L+l 等で Safari のアドレスバーにフォーカスなどのネイティブショートカットも生かしたいのです。

**Comment by iMasanari** [comment]
⌘英かなの方法では、修飾キーが押された時のイベントでは左右を判断することができますが、他のキーが押された時のイベントでは既に押されている修飾フラグの左右を判断することができません。

なので実装するには新しい方法を探すか無理やり実装するという形になるため、時間がかかると思われます。

**Comment by MasaYan24** [comment]
そうなのですね、技術的なことは分かりませんが、新しい方法を考えるのは大変そうですね。
ご返信ありがとうございました。
