### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by iiiGerardoiii** [iMasanari/cmd-eikana#12]
Hopefully someone who speaks japanese and english help us with the translation.

Google translation: うまくいけば、日本語と英語を話す人が翻訳を助けます。

**Comment by Mkohm** [comment]
English version would be very much appreciated.

**Comment by martinklepsch** [comment]
Yes please :+1:  😄

**Comment by martinklepsch** [comment]
@iMasanari Hello :) Would you be interested in translating the app to English entirely or would you like to continue supporting Japanese? I was just thinking I could go through the code and search for the strings, use Google Translate and replace with appropriate English versions but there would only be support for one language.

Is there some i18n stuff setup in this project that contains a dictionary with the relevant messages/texts? Or are there plans to add such thing?

---

@iMasanariこんにちは:)あなたはアプリを完全に英語に翻訳することに興味がありますか、または日本語をサポートし続けたいですか？ コードを読み込んで文字列を検索し、Google翻訳を使用して適切な英語版に置き換えることができると思っていましたが、1つの言語のみのサポートがあります。

関連するメッセージ/テキストを含む辞書が含まれているこのプロジェクトには、いくつかのi18nの設定がありますか？ あるいは、そのようなものを追加する計画はありますか？

**Comment by KAMIKAZEUA** [comment]
Please ENG!

**Comment by hbrls** [comment]
FYI, non-Japanese speakers.

![screen shot 2017-02-27 at 1 51 05 pm](https://cloud.githubusercontent.com/assets/1220476/23350382/0f51be88-fcf5-11e6-9e20-92e3cd07b26c.png)

**Comment by KAMIKAZEUA** [comment]
Well, app is very simple, so this new version dialog I first time hit cancel), but next time I downloaded update. But anyway EN localization is needed.

**Comment by asmeurer** [comment]
It's kind of silly, but the Google Translate iOS app (probably Android too) lets you point your camera at the screen and it translates the Japanese directly. It's not amazing, but it's good enough to get an idea of what the different things mean. 
![2017-03-12 18 44 09](https://cloud.githubusercontent.com/assets/71486/23836783/30f60a80-0754-11e7-8849-98c42a65c2f1.png)

**Comment by imagine** [comment]
Master branch has English but it's not released yet

**Comment by ryofurue** [comment]
I guess this issue should be closed? Everything on this app (except for the name of the app) is English now on my system, macOS Sierra.  My default system language is English.

**Comment by imagine** [comment]
The app name should get localized too e.g. for easy Spotlight launching. CFBundleName
