### ISSUE TITLE
PowerPoint でマウス操作が不安定になる不具合

### ISSUE THREAD

**Issue by do-gugan** [iMasanari/cmd-eikana#15]
いつも有り難く使わせていただいています。
PowerPoint for Mac（15.29.1）でちょっとおかしな挙動を発見したので報告します。
例えば左サイドバーのスライドサムネイル一覧でいくつかのサムネイルを連続クリックすると、当然フォーカスがそこに移っていくわけですが、⌘英かなが起動した状態でそれをすると、言葉で説明は難しいのですがスライド間をクリックした時の横線カーソルがチラチラ出たり、スライドの順が勝手に入れ替わったりします。雰囲気的にはドラッグ判定になっているというか、マウスアップが通ってないというか...
また逆に、テキストを範囲選択する為にドラッグしている時、勝手にマウスダウン継続が中断されるのか、意図しないワードが選択されそれをドラッグして他の位置にドロップしてしまう結果になることもあります。
⌘英かなを終了すると即座に収まります。使用バージョンは2.2.0です。
今は安全の為PowerPoint作業時は終了していますが、もし改善の参考にしていただければ幸いです。

**Comment by jyokyoku** [comment]
PowerPointではありませんが、intelliJを利用中に同様の不具合を確認しました。

一定の間隔でマウスをクリックしながらカーソルを移動すると、
ドラッグ動作と同様の挙動になってしまうようで、
クリック→クリックまでの間にカーソルが移動した範囲のコードが選択された状態になります。

最初はマウスのチャタリングかと思っていたのですが、
こちらも「⌘英かな」を終了すると収まり、同現象は発生しなくなります。

MacOS Sierra 10.12.3
⌘英かな：2.2.0
利用マウス：Logicool MX Master（Unifyng接続）

**Comment by jin0g** [comment]
同様のドラックドロップ判定の現象を、PowerPoint、カレンダー、ターミナル、でも確認しました。

マウス、トラックパッド関係なく確認できます。
また、⌘英かな 1.0.4でも問題を確認しました。
1.0.2では問題が発生しないため、バージョンを下げて使っています。

**Comment by iMasanari** [comment]
報告ありがとうございます。

ターミナルにてバグの再現を確認いたしました。
v1.0.2では問題が発生しないとの報告通り、マウス取得部分を旧ver.の方法にしたところターミナルでは問題は発生しませんでした。

PowerPoint for Mac、intelliJを持っておらず確認ができないため、v2.2.1で確認していただけると幸いです。

**Comment by jyokyoku** [comment]
修正対応ありがとうございました、Ver2.2.0にてIntelliJを利用してみましたが、
問題が解決していることを確認しました。
他のアプリケーションでも念のため確認していますが、問題はなさそうです。
大変便利に利用出来ております、ありがとうございます。
