### ISSUE TITLE
a button on preference window maybe misplaced.

### ISSUE THREAD

**Issue by watr** [iMasanari/cmd-eikana#19]
"Button" titled button on "Preferences..." -> "Setting" maybe misplaced.
If I click this button, nothing happens. 🤔 

 Please remove this "Button". (If I’m not wrong.)

<img width="562" alt="cmd-eikana_preferences_setting" src="https://cloud.githubusercontent.com/assets/94398/23493756/76ee025a-ff51-11e6-9eac-257d1990318b.png">

**Comment by iMasanari** [comment]
Thank you for the report.
Although I forgot to erase it, I fortunately push it has no effect.
We will fix it at the next update.

**Comment by watr** [comment]
Thanks!
Fixed with Eikana v2.2.2

いつも便利に使っています!
対応ありがとうございました。
