### ISSUE TITLE
Support 3 or more languages at a time

### ISSUE THREAD

**Issue by kittinunf** [iMasanari/cmd-eikana#28]
Hey, first of all, thank you so much for this. I couldn't tell you how many times I feel annoyed when I have to switch between English and Japanese in one sentence. The default key is counter-intuitive. `cmd-eikana` is a life saver. Thanks a lot.

Speaking of that, I do have a feature request. As I currently have 3 keyboards on my mac (as a native Thai living in Japan, I do have Thai, English, Japanese layouts on my mac), I find it annoying for switching to the 3rd language, do you think it is something you want to support in the future?

If this goes along with your vision for the project, I am more than happy to help you contribute this by open a PR to add this feature. 

Of the top of my head, I think solution could be about something like 

```
l-cmd: (default) Eng -> press again -> Thai ....
r-cmd: (default) Jap -> press again -> Thai ....
```

or to generalize it

```
l-cmd: (default) Lang1 -> press again -> Lang3 -> press again -> Lang4 ... (until you exhaust the list then go back to default)
r-cmd: (default) Lang2 -> press again -> Lang3 -> press again -> Lang4 ... (until you exhaust the list then go back to default)
```

What do you think?

**Comment by iMasanari** [comment]
Eikana is a key remap application.
We use the eisuu key and the kana key on the Japanese keyboard to switch languages, but probably not the key to switch to another specific language.

Therefore, there is no plan to add a function to switch to other languages.


But switching seems to be possible with `TISCreateInputSourceList` and `TISSelectInputSource`.

Also, it does not correspond to the operation of command key only, but there seems to be an application.
https://github.com/utatti/kawa
