### ISSUE TITLE
「ログイン後にこのアプリを起動」が効かない

### ISSUE THREAD

**Issue by Anko777** [iMasanari/cmd-eikana#29]
「ログイン後にこのアプリを起動」にチェックを入れていても、OS起動時やログイン時にアプリが起動しません。

OS: Sierra 10.12.6

**Comment by iMasanari** [comment]
もう一度チェックを外す→入れるをして再起動をしたあと、コンソール.appを開き、検索で「eikana」のログが無いか確かめてください。

また、開発中に遭遇したアプリが自動起動しない条件として、英かなが2つインストールされている（アプリIDの重複）ことがありました。その時は、コンソール.appに10秒ごとにログが出力されてました。念のためこちらも確認お願いします。
