### ISSUE TITLE
Backing up the settings

### ISSUE THREAD

**Issue by hisyam** [iMasanari/cmd-eikana#33]
How do I backup all the keyboard shortcuts? I need to do a clean install of macOS because High Sierra is really buggy.

Thanks.

**Comment by iMasanari** [comment]
Thank you for using the ⌘Eikana.

The configuration file is located in the following location.

```
~/Library/Preferences/io.github.imasanari.cmd-eikana.plist
```

After placing it in the same place, you can restore it by launching the application.  
(It may be necessary to start up the application and overwrite the setting file if it exists, and restart the Mac)

---
⌘英かなを使ってくださりありがとうございます。

設定ファイルは以下の場所にあります。

```
~/Library/Preferences/io.github.imasanari.cmd-eikana.plist
```

同じ場所に配置した後、アプリを起動することで復元できます。
（すでにアプリを起動し設定ファイルがある場合は上書きし、Macを再起動する必要があるかもしれません）

**Comment by hisyam** [comment]
Thanks!
