### ISSUE TITLE
Ctrl+Commandで空白のinvalid characterが入力されてしまう

### ISSUE THREAD

**Issue by rimpeichiba** [iMasanari/cmd-eikana#40]
大変お世話になっています．
以前から英かなを起動中に，任意のテキストエディターでctrl+commandを入力すると空白のinvalid characterが生成されてしまうのですが，何か対応策をご存知でしょうか？（英かなを終了すると問題は解決します）
私はUS配列のキーボードを搭載したmacBookProを用いています．OSはBig Sur 11.2.1です．

**Comment by iMasanari** [comment]
ご報告ありがとうございます。

調査の結果、下記の条件でControl押下中に「Command_R」を押下すると、制御文字 `\u0010` が入力されることがわかりました。

- Mac標準のIM「日本語 - ローマ字入力」を使用し、入力モード「カタカナ」にチェックが入っている
- 「Command_R」を「かな」に割り振っている

この症状と同じ場合、下記が解決方法になると思います。

1. メニューバー[⌘]アイコン → [Prefarence...] → [キーリマップ] の[+]ボタンから、次の設定を追加する
  input: `^Command_R` ※実際にそのキーを入力
  output: `Disable` ※ドロップダウンから選択
1. 上記設定の[menu]から[1つ上に移動]を選択し、「Command_R → かな」よりも上にする

<img width="447" alt="スクリーンショット 2021-08-12 8 50 46" src="https://user-images.githubusercontent.com/20771486/129120525-5abeff80-4a1f-46b4-a656-8799d2f4b736.png">

なお、Mac標準の日本語キーボードを使用した際に、Control+「かな」で上記文字が入力されるか（Control+「かな」の動作として、制御文字`\u0010`が入力されることが正しいか）は調査できていません。

**Comment by rimpeichiba** [comment]
早速のご返信ありがとうございます．
お教えいただいた方法で問題解決できました．
ctrl+commandを用いたショートカットキーを多用していたので，とても助かります．

**Comment by michihisa** [comment]
いつも「⌘英かな」にお世話になっております。
これは補足となりますが、私も似た症状に悩まされておりまして、同様の方法で問題解消しましたのでご報告させていただきます。

環境: MBP2018, macOS Big Sur（11.5.2）, US配列キーボード（およびBluetoothのUS配列キーボードでも発生）

私の場合は、Ctrl + Command_R ではなく Ctrl + Command_L で制御文字 `\u0010` が入力されました。さらに `Ctrl` だけでなく `Shift`, `Opt`, `fn` と Command_L のコンビネーションでも同様に `\u0010` が入力されました。
（余談ですが、私が普段使っているVS Codeですと `\u0010` は `DLE` (DATA LINK ESCAPE) という制御文字となって表現されます）

解決策としては同じで、キーリマップに `Ctrl`, `Shift`, `Opt`, `fn` それぞれについて Command_L とのコンビネーションを `Disable` とする設定を追加し、一番上に持ってくるだけです。
以上、ご報告となります。
