### ISSUE TITLE
Windows Remote Desktop環境にて「英数」outputが「`」となる

### ISSUE THREAD

**Issue by kh51** [iMasanari/cmd-eikana#41]
いつもありがたく使わせていただいております。
以下、仕様かもしれませんが不便な現象に遭遇しましたので質問させていただきます。

[環境]
  接続元:
  - ⌘英かな 2.2.3
  - macOS Mojave 10.14.6
  - MS Remote Desktop 10.6.8(1914)
  
  接続先:
  - Windows 10
  
[事象]

  上記環境にて、macからWindowsへリモートデスクトップ接続をしています。
  
  その際、接続先のWindows上で、英かなで「英数」をoutputに指定したキーを押すと、「`」文字が入力されます。
  例えば、input:「Option_L」、output: 「英数」を設定すると、リモート接続先のWindows上でOption_Lを押すと「`」が入力されます。「かな」を設定しているキーは特に文字が入力されるようなことはありません。

これは仕様でしょうか。
「`」が入力されないような設定方法があればご教示いただけませんでしょうか。

どうぞよろしくお願いいたします。

**Comment by iMasanari** [comment]
⌘英かなには、特定のアプリでリマップ設定を無効化することができます。
下記の方法で、MS Remote Desktop中は⌘英かなを無効化する方法で解決できないか、お確かめください。

1. MS Remote Desktopを起動し、画面を一度、アクティブにしておく
2. メニューバーの「⌘」から「Preferences...」を選び、⌘英かなの設定画面を開く
3. 設定画面の「除外アプリ」から、MS Remote Desktopを探し、チェックをつける

なお、アプリ個別の無効化はできますが、個別のキーリマップ設定には対応していませんので、ご了承ください。

**Comment by kh51** [comment]
除外アプリ設定にて回避できました！
ご教示ありがとうございました。
引き続きありがたく使わせていただきます。
今後ともよろしくお願いいたします。
