### ISSUE TITLE
Request: implementation overview

### ISSUE THREAD

**Issue by irliao** [iMasanari/cmd-eikana#6]
I just started learning Swift and is wondering if you can briefly explain your code in KeyEvents.swift?

I would like to refactor your App to use single left-Shift to output "(", single right-Shift to output ")", left/right-Shift + key to output default Shift behavior.

Thank You!

**Comment by iMasanari** [comment]
I'd like to be able to customize the modifier key single movement in the next version.
Please rewrite with reference to the following case can not wait is!

[KeyEvent.swift#L64](https://github.com/iMasanari/cmd-eikana/blob/0332a8b976cce889868f7dcffd991f6d14a3d68c/cmd-eikana/KeyEvent.swift#L64) is the function that is called when the state of the modifier key has changed.
Number of [#L65](https://github.com/iMasanari/cmd-eikana/blob/0332a8b976cce889868f7dcffd991f6d14a3d68c/cmd-eikana/KeyEvent.swift#L65) line and [#L73](https://github.com/iMasanari/cmd-eikana/blob/0332a8b976cce889868f7dcffd991f6d14a3d68c/cmd-eikana/KeyEvent.swift#L73) line is the key code of the command key.
If you change it to the 56 and 60 will change to the shift key.

When the key is moved away [inputJisEisuuKey](https://github.com/iMasanari/cmd-eikana/blob/0332a8b976cce889868f7dcffd991f6d14a3d68c/cmd-eikana/KeyEvent.swift#L41) and [inputJisKanaKey](https://github.com/iMasanari/cmd-eikana/blob/0332a8b976cce889868f7dcffd991f6d14a3d68c/cmd-eikana/KeyEvent.swift#L50) will be called.
102 and 104 of them is the key code of the jis-eisuu and jis-kana.
Please rewrite the there!

**Comment by irliao** [comment]
@iMasanari Thank you so much for the response! :)
