### ISSUE TITLE
JISキーボードの変換、無変換、あるいは左右のコントロールキーでのサポート

### ISSUE THREAD

**Issue by iMasanari** [iMasanari/cmd-eikana#7]
> 私もKarabinerユーザーでしたが、よりシンプルなこのソフトを発見し使用していますが、キーボードとしてPC用のJISキーボードの変換、無変換、あるいは左右のコントロールキーで同じ機能をサポートできないでしょうか？

https://github.com/iMasanari/cmd-eikana/issues/1#issuecomment-250036642

**Comment by iMasanari** [comment]
変換、無変換キーの対応はまずないと思います。おそらくローレベルな（機械に近い）ところを扱う必要があり、キーボードの仕様が変わった時に素早く対応できない可能性があります。これはシンプル故に早いという、機能が豊富なKarabinerに対して私が思う利点に反していると考えているからです。変換、無変換キーはKarabiner-Elements (OS X 10.12)やSeil (~OS X 10.11)を使用してください。

一方で、コントロールキーの方はキーコンフィグとして実装予定です。他の修飾キーも単体押しで英数/かな、もしくは他のキーコードに変更できるように調整中です。しばらくお待ちください。

**Comment by matsuda0707** [comment]
了解しました。今は、コマンドキーを右、左と交互に押すようになっていますが、同じコマンドキーを連打でON/OFFには出来ないのでしょうか？コントロールキーの件、ありがとうございます。コントロールキーでも連打で、ON/OFF出来ると良いですね。

**Comment by iMasanari** [comment]
ver.2.0.0 (22aeb01b99bbf817d37e72fb0be4d1c71ccf66d7) にて修飾キーのキーコンフィグを実装しました。英数・かなのトグルは⌘スペース（環境によっては^スペース）で代用できるかと思います。
