### ISSUE TITLE
カタカナ入力モードについて

### ISSUE THREAD

**Issue by butakku** [iMasanari/cmd-eikana#8]
ver 2.0にアップデードしましたが、shift + 右cmdでのカタカナ入力モードの発動が起こらないようです。
特定の環境で起こる事象なのかどうかはわかりませんが、お時間のあるときに調べていただけると幸いです。

**Comment by iMasanari** [comment]
@butakku `shift + かな`でカタカナモードになる機能があるんですね！ 初めて知りました！
原因は機能を追加していく中で、こちらの都合で修飾キーをリセットしてかなキーのkeyCodeを送信するようにしたせいではないかと思います。次のアップデートで修正しますので、しばらくお待ちください。
